name: Build Shiny Docker Image and Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:

  deploy:
    name: Build and deploy pubbias app
    runs-on: ubuntu-latest
    # Commit message needs to contain 'deploy evalue' to trigger the job
    if: "contains(github.event.head_commit.message, 'deploy')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and push Docker to Heroku
        uses: akhileshns/heroku-deploy@v3.11.10
        with:
          # app directory needs to be set relative to root of repo
          appdir: "app"
          # this is the Heroku app name you already set up in dashboard
          heroku_app_name: pubbias
          # secrets need to be added to the GitHub repo settings
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: true # don't change this
